name: GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run gh-pages
      - uses: EndBug/add-and-commit@v9
        with:
          commit: --no-verify
          new_branch: gh-pages-test
